name: continuous-integration
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.x'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./server/requirements.txt
      - name: run-tests
        run: |
           chmod +x ./server/requirements.txt
           chmod +x ./run_style_checker.sh
           ./run_style_checker.sh
           chmod +x ./run_unit_integration_tests.sh
           ./run_unit_integration_tests.sh
      - name: commit tests
        run: |
          git config --global user.name ${GITHUB_ACTOR}
          if [ ${GITHUB_ACTOR} = "tojoabella" ]
          then
            git config --global user.email "terricabella@gmail.com"
          fi
          git add ${GITHUB_WORKSPACE}/reports/tests/*
          git add ${GITHUB_WORKSPACE}/reports/style_bug_checker/*
          git commit -m "ci style and unit tests for latest push"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "6e5c3723-c89d-4425-8397-ad6db5836fa7"
          heroku_app_name: "tp-leads-app"
          heroku_email: "animesh.bhasin@columbia.edu"
          appdir: server
