name: run-tests

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script files
      run: |
         chmod +x ./run_style_checker.sh
         ./run_style_checker.sh
         chmod +x ./run_unit_integration_tests.sh
         ./run_unit_integration_tests.sh
      shell: bash
